### ISSUE TITLE
release question generation model

### ISSUE THREAD

**Issue by xixi019** [yhshu/Distribution-Shifts-for-KBQA#1]
Dear authors,
Thank for you releasing the code. 
Do you have a plan to upload the trained model on question generation?

**Comment by yhshu** [comment]
Thanks for your interest. I'll check it and respond later after spring break.

**Comment by yhshu** [comment]
Hi,
I've updated README, and you could visit HF models for these checkpoints: 
- https://huggingface.co/yhshu/GAIN-logical-form-question-generation/
- https://huggingface.co/yhshu/GAIN-triple-question-generation/

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
DarthVanger, @otang, @niuxdexiaobai, @hanpfei, @itenceMgr, @Taiwotosin09, @TomsKrauklis, @codemilli, @zhengjia1984, @Codecwzz, @zhongyin, @lichao23, @BuknSS, @msafi, @NikeGOGO, @hackerain, @A0dh, @AiltonSavio, @xiyanghh, @lansign, @ender233, @ssayu, @satoshiware, @stickystrange, @nuhkoca, @gnikh, @whbcusts, @odednaor, @muhammmmmm123, @abalanian, @orungrau, @jjunhyub, @woniu123360, @Carterbluth, @KotaAoyama, @orionsread, @abbish, @lindadoudou, @Gandalf-Pl, @lxstorm, @edgarMejia, @William0517, @tezukzai, @fonsnp, @hoverruan, @murtza, @YakinRubaiat, @acidiney, @melmar12, @diwawa
